apiVersion: v1
kind: Namespace
metadata:
  name: pythonapp
  labels:
    app.kubernetes.io/name: pythonapp
    helm.sh/chart: pythonapp-0.1.0
    app.kubernetes.io/instance: pythonapp-helm-chart
    app.kubernetes.io/managed-by: Helm
spec: {
  "finalizers": [
    "kubernetes"
  ]
  
}