{{- if .Values.secretMessage.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pythonapp-helm-chart.fullname" . }}-secretmessage
type: Opaque
data:
  MENSAJE: {{ .Values.secretMessage.message | b64enc | quote }}
{{- end }}