{{- if .Values.PersistentVolume.enabled -}}
apiVersion: v1
kind: PersistentVolume
namespace: python-app-ns
metadata:
  name: {{ include "helm-chart.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.PersistentVolume.size}}  # Asegúrate de cambiar esto según tus necesidades
  accessModes:
    - {{ .Values.PersistentVolume.accessMode}}
  persistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /app/python-app
{{- end}}