{{- if .Values.secretMessage.create }}
apiVersion: v1
kind: Secret
namespace: {{ .Release.Namespace }}
metadata:
  name: {{ include "helm-chart.fullname" . }}-secret
type: Opaque
data:
  MENSAJE: {{ .Values.secretMessage.message | b64enc | quote }}
{{- end }}