{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
namespace: python-app-ns
metadata:
  name: {{ include "helm-chart.serviceAccountName" . }}-sa
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
